INSERT INTO ELIGIBILITY_DTLS (ELIG_ID, PLAN_NAME, PLAN_STATUS, BENEFIT_AMT, START_DATE, END_DATE) VALUES (101,'SNAP','Approved',1500.56,'2020-05-30','2022-05-13');
INSERT INTO ELIGIBILITY_DTLS (ELIG_ID, PLAN_NAME, PLAN_STATUS, BENEFIT_AMT, START_DATE, END_DATE) VALUES (102,'SNAP','Approved',1300.74,'2021-05-30','2022-05-30');
INSERT INTO ELIGIBILITY_DTLS (ELIG_ID, PLAN_NAME, PLAN_STATUS, DENIAL_REASON) VALUES (103,'SNAP','Denied', 'High Salary Income');
INSERT INTO ELIGIBILITY_DTLS (ELIG_ID, PLAN_NAME, PLAN_STATUS, DENIAL_REASON) VALUES (104,'SNAP','Denied', 'High Rent Income');

INSERT INTO ELIGIBILITY_DTLS (ELIG_ID, PLAN_NAME, PLAN_STATUS, BENEFIT_AMT, START_DATE, END_DATE) VALUES (105,'CCAP','Approved',1400.23,'2021-05-30','2022-04-17');
INSERT INTO ELIGIBILITY_DTLS (ELIG_ID, PLAN_NAME, PLAN_STATUS, BENEFIT_AMT, START_DATE, END_DATE) VALUES (106,'CCAP','Approved',1100.45,'2020-05-30','2021-03-30');
INSERT INTO ELIGIBILITY_DTLS (ELIG_ID, PLAN_NAME, PLAN_STATUS, DENIAL_REASON) VALUES (107,'CCAP','Denied', 'Kids Not Available');
INSERT INTO ELIGIBILITY_DTLS (ELIG_ID, PLAN_NAME, PLAN_STATUS, DENIAL_REASON) VALUES (108,'CCAP','Denied', 'Kids Age Above 16 Years');

INSERT INTO ELIGIBILITY_DTLS (ELIG_ID, PLAN_NAME, PLAN_STATUS, BENEFIT_AMT, START_DATE, END_DATE) VALUES (109,'Medicaid','Approved',2400.23,'2021-04-30','2022-05-17');
INSERT INTO ELIGIBILITY_DTLS (ELIG_ID, PLAN_NAME, PLAN_STATUS, BENEFIT_AMT, START_DATE, END_DATE) VALUES (110,'Medicaid','Approved',3500.45,'2020-03-30','2021-01-21');
INSERT INTO ELIGIBILITY_DTLS (ELIG_ID, PLAN_NAME, PLAN_STATUS, DENIAL_REASON) VALUES (111,'Medicaid','Denied', 'High Income');
INSERT INTO ELIGIBILITY_DTLS (ELIG_ID, PLAN_NAME, PLAN_STATUS, DENIAL_REASON) VALUES (112,'Medicaid','Denied', 'High Property Income');

INSERT INTO ELIGIBILITY_DTLS (ELIG_ID, PLAN_NAME, PLAN_STATUS, BENEFIT_AMT, START_DATE, END_DATE) VALUES (113,'Medicare','Approved',8400.23,'2020-02-27','2022-07-17');
INSERT INTO ELIGIBILITY_DTLS (ELIG_ID, PLAN_NAME, PLAN_STATUS, BENEFIT_AMT, START_DATE, END_DATE) VALUES (114,'Medicare','Approved',4500.45,'2020-01-30','2021-04-30');
INSERT INTO ELIGIBILITY_DTLS (ELIG_ID, PLAN_NAME, PLAN_STATUS, DENIAL_REASON) VALUES (115,'Medicare','Denied', 'High Income');
INSERT INTO ELIGIBILITY_DTLS (ELIG_ID, PLAN_NAME, PLAN_STATUS, DENIAL_REASON) VALUES (116,'Medicare','Denied', 'Age not matching');

INSERT INTO ELIGIBILITY_DTLS (ELIG_ID, PLAN_NAME, PLAN_STATUS, BENEFIT_AMT, START_DATE, END_DATE) VALUES (117,'QHP','Approved',5621.2,'2021-07-30','2022-09-17');
INSERT INTO ELIGIBILITY_DTLS (ELIG_ID, PLAN_NAME, PLAN_STATUS, BENEFIT_AMT, START_DATE, END_DATE) VALUES (118,'QHP','Approved',8569.45,'2020-08-30','2021-07-30');
INSERT INTO ELIGIBILITY_DTLS (ELIG_ID, PLAN_NAME, PLAN_STATUS, DENIAL_REASON) VALUES (119,'QHP','Denied', 'Expired');
INSERT INTO ELIGIBILITY_DTLS (ELIG_ID, PLAN_NAME, PLAN_STATUS, DENIAL_REASON) VALUES (120,'QHP','Denied', 'Expired');